In [1]:
import pandas as pd
from Bio.SeqUtils import gc_fraction

In [2]:
###Define important sequence###
###PDR1 promoter sequence 40bp###
pdr1_prom = 'cagccaagaatatacagaaaagaatccaagaaactggaag'
###PDR1 coding sequence###
pdr1_seq = 'atgcgaggcttgacacctaagaacggtgtacatattgagacgggtccggatacagaatcgtccgcggactccagcaacttttctacaggtttcagcggcaagattcgtaagccaaggtcgaaagtaagtaaagcgtgcgataactgtagaaaaagaaagataaaatgtaatgggaagtttccctgcgcaagctgtgagatatattcatgtgagtgcacgttcagcactagacaaggtggcgctcgaataaaaaaccttcacaagacgagtttggaaggtacaaccgtacaagtcaaagaggaaacagattccagttcgacttctttttctaatcctcagcgatgtacagacgggccatgcgcagtggaacaaccaacgaaattttttgagaatttcaagctaggtggtcgtagtagtggtgataatagcggaagtgatgggaagaatgacgacgatgtgaatagaaacggtttttatgaagacgatagcgaatcacaggcaactttgacatctctacaaaccactctgaaaaatttgaaggagatggctcatttaggtacacatgtaacctcagccatcgagagcattgaacttcagataagtgacttgcttaagcgatgggaacccaaagtgaggaccaaagaattagcaacaacgaaattttaccctaataaatcaatagaaactcaattgatgaaaaacaaatactgtgatgtggtacatttgacaagatatgccgcttggtcaaacaataagaaggaccaagatacttctagtcaacctttgatcgacgaaatctttggtttgtactctcctttccaatttttgtcacttcaaggtattggtaaatgtttccaaaattatagatccaaatccaaatgcgagatttttcccaggaccgccaaggaaaccatatacatcatgttaaggtttttcgacgtttgttttcatcacatcaaccaaggctgtgtctccatagctaatcccctggaaaactacctacagaaaatgaatcttttaccttcaaccccatcttcgatatcatctgcagggagcccgaatacagcacacacaaaatcgcatgttgcgttagtgataaatcacttaccgcagccctttgtgagaaatataaccggaataagtaattctgagctactaagcgaaatgaataatgatatcagcatgtttggcattttattgaagatgttggatatgcataaaaattcctaccagaacttcctaatggaaatcacatctaacccctccgtggctaaaaacacgcagtcaattgatgtcttgcaggaattcatccattattgtcaagctggagaggcgctaatcgccttatgttacagctattataattctacattatacaactacgtggacttcacatgcgacataacgcatttagagcaacttctatactttttggatctgctattttggctatcggaaatatacggttttgaaaaagtcttgaacgtagcagttcattttgtttcaagagttggtttatcaaggtgggaattttacgtgggtcttgatgaaaactttgctgaaagaagaagaaatctctggtggaaagctttctatttcgagaaaactttagcctctaaacttggctatccttcgaacattgatgactccaaaatcaattgtttattacctaagaattttcgagatgttgggttcttggataatagagattttatcgagaacgtccacttagttcgcaggagcgaagcttttgacaacatgtgcatatccgacttaaaatactatggcgaattagctgtcttacaaatagtcagccatttctcatcatctgttttattcaatgaaaaattcacgtcaattaggaatacatcaaaaccatctgttgttagagagaaactactcttcgaggtactcgagatttttaacgaaacagaaatgaaatatgatgctatcaaagagcaaactggaaaattgttcgatattgcattctctaaagatagtactgaactcaaagtttcaagagaggataagattatggcttcaaaatttgttctattttacgagcaccatttctgcagaatggttaacgaatctgataatattgtcgccagattatgcgtgcacagaaggccctcaatactaattgaaaacttgaaaatataccttcacaagatttacaaatcatggaccgatatgaacaaaatcttattagactttgacaacgattattccgtataccgttcgttcgcccattattctatcagttgcattattttggtatcacaagcattctcagtggccgaattcattaaggtaaatgacgttgtgaatatgattagagtcttcaaaagatttttggatataaaaattttttccgaaaatgagaccaatgagcatgtcttcaacagccaaagctttaaagactatacaagagctttttctttcctgacaatcgtcactcgtatcatgcttttggcatacggagagtcctctagcaccaacctcgatgttatctccaaatatattgatgagaatgcgccagatttaaaaggtataatagaacttgtcttggatacaaactcttgcgcttatcgatttttattagaacctgttcagaagtcaggattccatttaacggtctcacaaatgttgaaaaatagaaagtttcaggaaccactaatgtcaaatgaagataataagcagatgaagcataattcgggaaaaaatttgaatccggatctcccaagtcttaagacgggcacttcatgcttactaaatggcattgaatcgcctcaattgccattcaatggtcgctcagcaccttccccagtgagaaacaactcactaccggagtttgcacaattgccttcatttaggtcattatccgtgtctgatatgatcaatcccgattacgcgcaaccaacaaatgggcaaaataatacgcaagtccaatctaataaaccaatcaatgctcagcagcaaatacccacttcagtacaagtaccatttatgaacacaaatgaaatcaataacaacaacaacaacaacaacaacaataaaaacaatattaacaatattaacaacaacaacagtaacaatttttctgcaactagttttaatttggggacactagatgaatttgttaataacggtgatcttgaggacctctacagtatcctgtggagcgacgtttatccagatagt'.upper()
###PDR1 terminator sequence 4bp###
pdr1_ter = 'taaa'
###module here as 6 pb between the BSaI site###
basI_mod = 'GGAGACCgaagCTGGTCTCGACAG'
###PBS from Illumina on the i7 adapter###
pbs_i7 = 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'

In [16]:
### Split sequence in fragment of 75 pb and find the 20 pb before and the 4 after###

df_seq_split = pd.DataFrame(columns= ['aa_position', 'homo5prime', 'dms_part', 'homo3prime', 'bsaI_mod', 'pbsi7'])
lst_pos = tuple(range(0, 3200, 75))


for i in tuple(range(len(lst_pos))):
    
    if i == 42:
        
        df_seq_split.at[i, 'aa_position'] = str(int((lst_pos[i]+3)/3)) + '-' + str(1068)
        df_seq_split.at[i, 'homo5prime'] = pdr1_seq[lst_pos[i]-40:lst_pos[i]]
        df_seq_split.at[i, 'dms_part'] = pdr1_seq[lst_pos[i]:]
        df_seq_split.at[i, 'homo3prime'] = pdr1_ter
        df_seq_split.at[i, 'bsaI_mod'] = basI_mod
        df_seq_split.at[i, 'pbsi7'] = pbs_i7
        
    elif i == 0:
        
        df_seq_split.at[i, 'aa_position'] = str(int((lst_pos[i]+3)/3)) + '-' + str(int(lst_pos[i+1]/3))
        df_seq_split.at[i, 'homo5prime'] = pdr1_prom
        df_seq_split.at[i, 'dms_part'] = pdr1_seq[lst_pos[i]:lst_pos[i+1]]
        df_seq_split.at[i, 'homo3prime'] = pdr1_seq[lst_pos[i+1]:lst_pos[i+1]+4]
        df_seq_split.at[i, 'bsaI_mod'] = basI_mod
        df_seq_split.at[i, 'pbsi7'] = pbs_i7
        
    else:
        
        df_seq_split.at[i, 'aa_position'] = str(int((lst_pos[i]+3)/3)) + '-' + str(int(lst_pos[i+1]/3))
        df_seq_split.at[i, 'homo5prime'] = pdr1_seq[lst_pos[i]-40:lst_pos[i]]
        df_seq_split.at[i, 'dms_part'] = pdr1_seq[lst_pos[i]:lst_pos[i+1]]
        df_seq_split.at[i, 'homo3prime'] = pdr1_seq[lst_pos[i+1]:lst_pos[i+1]+4]
        df_seq_split.at[i, 'bsaI_mod'] = basI_mod
        df_seq_split.at[i, 'pbsi7'] = pbs_i7

In [17]:
###Save dataframe to csv file###

df_seq_split.to_csv('/Users/alexandre/Desktop/all_fragment_pdr1_40pb.csv', sep='\t')

In [19]:
###Load csv file with the different part of each fragment###
###Here the homo5prime for fragment13 have been increase to 91bp outside of the script###

df_seq_split = pd.read_csv('/Users/alexandre/Desktop/all_fragment_pdr1_40pb.csv', sep=',', index_col=0)
df_seq_split.head(15)

,aa_position,homo5prime,dms_part,homo3prime,bsaI_mod,pbsi7
0,01-25,cagccaagaatatacagaaaagaatccaagaaactggaag,ATGCGAGGCTTGACACCTAAGAACGGTGTACATATTGAGACGGGTC...,AACT,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
1,26-50,TGAGACGGGTCCGGATACAGAATCGTCCGCGGACTCCAGC,AACTTTTCTACAGGTTTCAGCGGCAAGATTCGTAAGCCAAGGTCGA...,AAAA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
2,51-75,GCCAAGGTCGAAAGTAAGTAAAGCGTGCGATAACTGTAGA,AAAAGAAAGATAAAATGTAATGGGAAGTTTCCCTGCGCAAGCTGTG...,ACTA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
3,76-100,CGCAAGCTGTGAGATATATTCATGTGAGTGCACGTTCAGC,ACTAGACAAGGTGGCGCTCGAATAAAAAACCTTCACAAGACGAGTT...,GAAA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
4,101-125,CAAGACGAGTTTGGAAGGTACAACCGTACAAGTCAAAGAG,GAAACAGATTCCAGTTCGACTTCTTTTTCTAATCCTCAGCGATGTA...,ACGA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
5,126-150,TCAGCGATGTACAGACGGGCCATGCGCAGTGGAACAACCA,ACGAAATTTTTTGAGAATTTCAAGCTAGGTGGTCGTAGTAGTGGTG...,GACG,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
6,151-175,TAGTAGTGGTGATAATAGCGGAAGTGATGGGAAGAATGAC,GACGATGTGAATAGAAACGGTTTTTATGAAGACGATAGCGAATCAC...,CTGA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
7,176-200,TAGCGAATCACAGGCAACTTTGACATCTCTACAAACCACT,CTGAAAAATTTGAAGGAGATGGCTCATTTAGGTACACATGTAACCT...,AGTG,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
8,201-225,ACATGTAACCTCAGCCATCGAGAGCATTGAACTTCAGATA,AGTGACTTGCTTAAGCGATGGGAACCCAAAGTGAGGACCAAAGAAT...,TCAA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
9,226-250,GACCAAAGAATTAGCAACAACGAAATTTTACCCTAATAAA,TCAATAGAAACTCAATTGATGAAAAACAAATACTGTGATGTGGTAC...,AATA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
10,251-275,TGATGTGGTACATTTGACAAGATATGCCGCTTGGTCAAAC,AATAAGAAGGACCAAGATACTTCTAGTCAACCTTTGATCGACGAAA...,TTGT,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
11,276-300,GATCGACGAAATCTTTGGTTTGTACTCTCCTTTCCAATTT,TTGTCACTTCAAGGTATTGGTAAATGTTTCCAAAATTATAGATCCA...,GCCA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
12,301-325,ctctcctttccaatttttgtcacttcaaggtattggtaaatgtttc...,GCCAAGGAAACCATATACATCATGTTAAGGTTTTTCGACGTTTGTT...,ATAG,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
13,326-350,CGACGTTTGTTTTCATCACATCAACCAAGGCTGTGTCTCC,ATAGCTAATCCCCTGGAAAACTACCTACAGAAAATGAATCTTTTAC...,GGGA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
14,351-375,GAATCTTTTACCTTCAACCCCATCTTCGATATCATCTGCA,GGGAGCCCGAATACAGCACACACAAAATCGCATGTTGCGTTAGTGA...,AATA,GGAGACCgaagCTGGTCTCGACAG,CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

In [5]:
###Import barcode file information###

bc_pdr1 = pd.read_csv('/Users/alexandre/Desktop/Projets/2023/IsabelleGArsenault/barcode_pdr1_fin.csv', sep='\t', index_col=0)
bc_pdr1.head()

                              seq  GC_content
0  NNACACGTACGGTANNACATCCGAGCTANN         0.5
1  NNCAGAGTGGTACANNACTCCAATCCTGNN         0.5
2  NNCTTGAGTGCCATNNAGTACGTTCTCGNN         0.5
3  NNGTGACACGTAACNNTACTAGCGAAGCNN         0.5
4  NNACACTCCTGCATNNACGTCGCAAGATNN         0.5

In [20]:
###Generate all opool by combining the different piece together and replacing the codon by NNK###

df_opool = pd.DataFrame(columns=['oPool', 'NNK_seq', 'to_order'])

for i in df_seq_split.index:
    
    DNA = df_seq_split.loc[i]['dms_part']
    DNA_length = len(df_seq_split.loc[i]['dms_part'])
    number_of_codons = int(DNA_length / 3)

    codon_list = []
    
    for j in range(number_of_codons) :
        
        codon_list.append(DNA[j *3 : j * 3 +3])
    
    hld1 = df_seq_split.loc[i]['aa_position'].split('-')[0]
    hld2 = df_seq_split.loc[i]['aa_position'].split('-')[1]
    
    hld3 = tuple(range(int(hld1), int(hld2)+1))
    
    for k in range(number_of_codons):
        
        codon_list2 = codon_list.copy()
        
        codon_list2[k] = 'NNK'

        seq = ''.join(codon_list2)
        
        df_opool.at[hld3[k], 'NNK_seq'] = seq
        df_opool.at[hld3[k], 'oPool'] = int(i+1)
        df_opool.at[hld3[k], 'to_order'] = df_seq_split.loc[i]['homo5prime'] + df_opool.loc[hld3[k]]['NNK_seq'] + df_seq_split.loc[i]['homo3prime'] + df_seq_split.loc[i]['bsaI_mod'] + bc_pdr1.loc[hld3[k]]['seq'] + df_seq_split.loc[i]['pbsi7']

In [21]:
###Save dataframe to csv file###

df_opool.to_csv('/Users/alexandre/Desktop/primerNNK_for_opool_40pb_F13_91pb.csv', sep='\t')